### PR TITLE
Added Appaloosa Service

### PR DESCRIPTION
**Pull request by tonybaroneee**
Internal topic branch based off the fine work of @jeremybdk from: #111

### CODE REVIEW

**Comment by jladieu** [comment]
:ship:

**Comment by jeremybdk** [comment]
Thank you !

Sent from my iPhone

On 08 Dec 2015, at 20:46, Anthony Barone <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #115<https://github.com/crashlytics/crashlytics-services/pull/115>.

-

**Comment by tonybaroneee** [comment]
No problem :) I'll let you know when it's live!

**Comment by tonybaroneee** [comment]
@jeremybdk Ok, all set! :)

image

**Comment by jeremybdk** [comment]
Thank you Anthony !

--
Jeremy Bodokh
Sent with Airmail


On 9 décembre 2015 at 17:47:02, Anthony Barone (notifications@github.com<mailto:notifications@github.com>) wrote:

@jeremybdk<https://github.com/jeremybdk> Ok, all set! :)

[image]<https://cloud.githubusercontent.com/assets/844249/11691773/8925f304-9e6a-11e5-9dcd-1b18c1b4a53b.png>

**Pull request merged**
