### PR TITLE
Added Appaloosa Service

### PR DESCRIPTION
**Pull request by jeremybdk**
If you need a test account let us know,

Best,

### CODE REVIEW

**Comment by jladieu** [comment]
@jeremybdk thanks for your submission - do you mind sending instructions for setting up a test account, as well as a link to the public API documentation for Appaloosa to support(at)fabric.io?

**Comment by jeremybdk** [comment]
The public API doc is here http://www.appaloosa-store.com/api

You can login using this test account  ( https://www.appaloosa-store.com/users/sign_in?locale=en )
email : cva+crashlytics@octo.com<mailto:cva+crashlytics@octo.com>
password : crashitlikeitshot

Let me know if you need anything else,

Best Regards,

Jeremy

--
Jeremy Bodokh
Sent with Airmail


On 17 novembre 2015 at 15:34:19, Josh Ladieu (notifications@github.com<mailto:notifications@github.com>) wrote:

@jeremybdk<https://github.com/jeremybdk> thanks for your submission - do you mind sending instructions for setting up a test account, as well as a link to the public API documentation for Appaloosa to support(at)fabric.io?

**Comment by jeremybdk** [comment]
Done,
Just sent everything by email to support.

**Comment by jladieu** [comment]
Thanks @jeremybdk - I think we have everything we need to get started, we just need to queue it up to integrate and test.  We will let you know when we've pulled the work to get this tested and integrated.

**Comment by tonybaroneee** [comment]
Closing in favor of this new branch for internal work: #115

**Pull request closed without merging**
