### PR TITLE
zoho projects integration

### PR DESCRIPTION
**Pull request by zohoproject**
We have done the zoho projects integration for crashlytics

### CODE REVIEW

**Comment by seandc** [comment]
@zohoproject Thanks for submitting this!  Do you mind adding some rspec tests?

**Comment by zohoproject** [comment]
@seandc Just added rspec tests. Please check it out.

**Comment by jladieu** [comment]
@zohoproject I was looking into this a little bit and tried using CURL to verify the HTTP requests that your code would be sending.  I ended up with a curl command something like this:
```
curl --verbose -X POST --data authtoken=authtoken --data pId=projectId --data pltype=chook --data payload=testing https://projectsapi.zoho.com/serviceHook
```
Can you confirm that this works with your account?  I can't seem to get it to work when I swap in my own authtoken and project ID.

Also, I was looking at the Zoho projects API documentation here: https://www.zoho.com/projects/help/rest-api/zohoprojectsapi.html

I couldn't find where the serviceHook path is documented; can you point me in the right direction?  Thanks!

**Comment by zohoproject** [comment]
In Zoho Projects, select the desired project, and then click Project Customization on the right side. Scroll down to view SERVICE HOOKS and copy the Project ID and Token value of GitHub Integration (we are going to use the same for this integrations as well)

Meanwhile please let us know the portal URL of Zoho Projects so that we can enable Enterprise Version, as in Free Version this option will not be available.

Thanks.

**Comment by jladieu** [comment]
Thanks @zohoproject - we will probably need to tweak the helptext to clarify that this integration is only available if you have an Enterprise Zoho account as it was confusing not to be able to find the section for service hooks.  I've set up a test account with the following portal URL: https://projects.zoho.com/portal/crashtest

**Comment by zohoproject** [comment]
Yes @jladieu We will have to update the help text. Once it is in release ready, we will update the help page as well as product page with relevant messages.

We have enabled Enterprise version for you account. Please test it now.

**Comment by jladieu** [comment]
Hi @zohoproject thanks for your help getting my account enabled for service hooks, I was able to get a 200 response code by submitting the following via curl, but didn't see anything in the projects dashboard.  Any advice?  Thanks!

```
curl --verbose -X POST --data authtoken=<removed> --data pId=<removed> --data pltype=chook --data payload='{"title":"fake title", "method": "fake method", "impact_level": 1, "impacted_devices_count": 1, "crashes_count": 1, "app": { "name": "fake app name", "bundle_identifier": "com.crashlytics.test", "platform": "android" }, "url" : "http://foo.com/bar" }' https://projectsapi.zoho.com/serviceHook
```

**Comment by zohoproject** [comment]
Hi @jladieu, Sorry for the delay in response. The payload passed doesn't have event key. That is the problem. We tried the below, It is working.

```
curl --verbose -X POST --data authtoken=<REMOVED> --data pId=<REMOVED> -- pltype=chook 
--data payload='{"event":"issue_impact_change","payload_type":"issue","payload":{"display_id": 569,"title":"Bug test from crashlytics","method":"crashlytics","impact_level":11,"crashes_count":20,"impacted_devices_count":29,"url":"http://crashlytics.com/full/url/to/issue"}}' https://projectsapi.zoho.com/serviceHook 
```

We too had an issue in our zohoprojects.rb file. We thought the payload itself will have event key. Now fixed the code. And we just checked in that change too.

**Comment by jladieu** [comment]
@zohoproject awesome - that sample CURL command worked.  Please give us some time to work on getting this integration merged and tested in our full test harness.  In the meantime, if you have edits you can provide for the helptext to better reflect that this is for enterprise zoho customers only, please amend or add to the PR and I'll get those picked up as we make progress.  I'll let you know if we encounter any bumps along the way getting the functionality integrated.

**Comment by zohoproject** [comment]
Thanks  @jladieu . Is it possible to share the test screenshot of Zoho Projects integration page in Crashlytics? And, Yes, we will update you with the changes in the help text if any.

**Comment by jladieu** [comment]
@zohoproject I'll get you a screenshot once I make a bit more progress on this next week. Thanks for all your hard work on this.  I'm closing out this branch and have created a new squashed branch on which  I'll base further work to get this integrated: https://github.com/crashlytics/crashlytics-services/pull/75

**Comment by jladieu** [comment]
Closing in favor of this new branch for internal work: https://github.com/crashlytics/crashlytics-services/pull/75

**Comment by zohoproject** [comment]
@jladieu 

 is it possible to give help link on error message of the integration?

We would like to give help link there. Please advise.

**Pull request closed without merging**
