### PR TITLE
Moxtra Service added

### PR DESCRIPTION
**Pull request by rajss**
Added Moxtra services integration.

### CODE REVIEW

**Comment by mikebonnell** [comment]
Thanks for submitting this Raj! There's a few things missing that need to be added before we can review this PR. Per our contributing guidelines - https://github.com/crashlytics/crashlytics-services/blob/master/CONTRIBUTING.md - we're also looking for a sample account that you can email into me. We also need to see RSpec tests, a logo for the service in the img/<service-name>.png. This logo will appear in the email we send when someone enables your integration. We also need an all white version of your logo in the img/<service-name>-mono.png folder. This logo will appear in the Settings dashboard configuration page.

Finally, these two items are also needed. A URL to your public API documentation that we can use while verifying the integration. Please also include your Twitter handle and a headshot we can use to credit you.

Let me know if you have any questions.

**Comment by rajss** [comment]
Hi Mike,
I have added the logo images. 
For a test Moxtra account, just go to https://beta.moxtra.com and sign up using your email. You will get full access.
URL to our public API documentation: https://developer.moxtra.com/docs/
My twitter handle is : @raj_sen_sharma
Where should I send the headshot?

Let me know if you need anything else.

**Comment by mikebonnell** [comment]
Thanks, you can send the headshot to me at support@ using our existing email thread :) 

The final item that is needed is RSpec tests for your PR. Here is an example to base yours off of: https://github.com/crashlytics/crashlytics-services/blob/master/spec/services/zohoprojects_spec.rb

**Comment by rajss** [comment]
Hi Mike,
Added the RSpec tests. I'll email you the headshot!

**Comment by mikebonnell** [comment]
Thanks, we will review this and get back to you with any feedback!

**Comment by jladieu** [comment]
@rajss I've started to look at running this in our integration test environment.  I've created https://github.com/crashlytics/crashlytics-services/issues/99 for my internal changes and will start working from there.  Please follow that branch for updates on our progress.  Thanks!

**Comment by jladieu** [comment]
@rajss This has been deployed, thanks so much for the excellent contribution!

**Comment by rajss** [comment]
Thanks Josh. That's awesome!

Cheers!
Raj.

**Pull request closed without merging**
