### PR TITLE
Update Redmine integration to support different issue types

### PR DESCRIPTION
**Pull request by rbad**

### CODE REVIEW

**Comment by rbad** [comment]
There were no conflicts when the pull request was made; is this little addition controversial? It would make the hook actually usable for those using Redmine in a more realistic setting (with 2 different issue types: features + bugs); at the moment all get added in as new feature tickets since the issue type can't be configured.

**Comment by jladieu** [comment]
Hey @rbad thanks for submitting this request!  This addition isn't controversial, but it requires a bit of testing and verification before we can make sure it doesn't impact our existing customer integrations.  We haven't yet figured out when we can slot this work in, but I'll certainly keep you posted when we can pull that work.

**Comment by jladieu** [comment]
Hey @rbad I'm hoping to get this work integrated soon!  I have a local copy that provides optional `status_id`, `tracker_id`, and `project_id` as parameters which I tested using the hostedredmine site  I'll update this issue once I get the change worked through our testing process and deployed.

**Comment by jladieu** [comment]
Hey @rbad this has been merged and deployed as part of this commit: https://github.com/crashlytics/crashlytics-services/commit/a4eafe5389e2ea8003eb3323e6cee6e90f15d2a1

Thanks so much for the contribution!

**Comment by rbad** [comment]
Thanks! Sadly, my team has moved to JIRA recently. 😢 
In any case, I have no doubt that this addition will be very useful for other teams using Redmine!

**Pull request closed without merging**
