### PR TITLE
Added ChatWork service

### PR DESCRIPTION
**Pull request by cw-ueno**
Like the slack integration you can send a notification to a ChatWork.

### CODE REVIEW

**Comment by jladieu** [comment]
@cw-ueno thank you so much for the PR, this looks great

It'll take us a little bit to pull in the changes.  Our next steps are to queue up this change for release and create a new internal working branch to make final tweaks and polish.  We'll keep you in the loop and may have some questions for you about ChatWork once we get started.

**Comment by cw-ueno** [comment]
@jladieu I got it. Please feel free to ask any questions about ChatWork. Thank you :smiley:

**Comment by jladieu** [comment]
Closing this PR in favor of the internal WIP branch here: https://github.com/crashlytics/crashlytics-services/pull/92

@cw-ueno we're working on getting this integrated in the next couple days, stay tuned!

**Comment by jladieu** [comment]
@cw-ueno - we got started on doing the work to test this out in our integration environment, but we got stuck while attempting to get an API Key.  Can you explain how we can acquire an API Key so we can keep moving forward on this?

On the subject, will API Keys be available for general purpose users?  We want to make sure any of our developers can use this new integration once we go live.  Thanks!

**Comment by cw-ueno** [comment]
@jladieu Would you please go to the following link (the page is Japanese) and click the green button to apply for our API Key. 
https://www.chatwork.com/service/packages/chatwork/subpackages/api/apply_beta_business.php
Also the API Key is available for general purpose, and you can utilize it for different integration purposes.
Thank you.

**Comment by jladieu** [comment]
Hey @cw-ueno, I went to this link awhile back (maybe a month ago?) and applied for the beta key, but then I don't think I ever received one -- any way you can have it resent?

Thanks!

**Comment by jladieu** [comment]
@cw-ueno - in case it helps locate my record, I applied for a beta key on June 4th using my Twitter email (same as my github screenname at twitter.com).  I received a confirmation from ChatWork but it didn't include a key I could use.

**Comment by mikebonnell** [comment]
@cw-ueno Mike stepping in for @jladieu We still haven't gotten access to the beta. Our review of this PR is blocked without it. Let me know if you're able to help out! I signed up with mbonnell (at) twitter (dot) com.

**Comment by cw-ishida** [comment]
Hi @jladieu & @mikebonnell , sorry for our late response. l'm Hayato from ChatWork US and let me support you on this. 
The API Key will not be sent via email, but it will be shown within ChatWork. 
Please log into ChatWork and go to "Personal Setting", which is under your logo on top-right-corner, and click the "API発行" tab to get your API Key. 
It's been a while since your request has been approved, you may be requested to put your password for ChatWork (It should be the same password as you used to log into ChatWork).  I am afraid that API Key tab is all in Japanese, and you may get confused, so please let me know if you have any question on this. Thank you.

**Comment by astronaughts** [comment]
Hi @jladieu & @mikebonnell,  I wanted to check in briefly to see if we can assist in any way with our API.  As Hayato described above, once your request has been approved, you can find the API key in ChatWork, under the "personal setting". Please don’t hesitate to reach out with any questions. Thank you.

**Comment by cw-ueno** [comment]
Hi @jladieu & @mikebonnell, I wanted to check in briefly to see if we can assist in any way with our API. As Hayato described above, once your request has been approved, you can find the API key in ChatWork, under the "personal setting". Please don’t hesitate to reach out with any questions. Thank you.

**Comment by JayKnightJWhitworth** [comment]
Here you go www.jayknightartpicpage.jayknightartpicpage.com/
On Jul 20, 2015 11:17 AM, "mikebonnell" <notifications@github.com> wrote:
>
> @cw-ueno Mike stepping in for @jladieu We still haven't gotten access to
the beta. Our review of this PR is blocked without it. Let me know if
you're able to help out! I signed up with mbonnell (at) twitter (dot) com.

**Comment by jladieu** [comment]
@cw-ishida I just wanted to let you know I was able to get to the API key as you described.  I'm resuming testing on this.  Thanks for your patience.

**Comment by jladieu** [comment]
@cw-ueno and @cw-ishida -- this has been deployed.  Thanks so much for this awesome work!

**Comment by jladieu** [comment]
@cw-ueno & @cw-ishida - we'd love to give you credit for this work on our marketing page https://try.crashlytics.com/integrations/ , can you provide a headshot we can use?

**Pull request closed without merging**
