### PR TITLE
Add Flock service

### PR DESCRIPTION
**Pull request by ayjindal**
This adds a service hook for integration with [Flock](https://www.flock.co).

Public API documentation is available [here](https://dev.flock.co/wiki/display/FlockAPI/Incoming+Webhooks).

I have also sent a mail for the account details that you can test with.

### CODE REVIEW

**Comment by mikebonnell** [comment]
Thanks @ayjindal. We got your email with the other details. Thanks for sending that over and we will keep you updated on this PR.

**Comment by ayjindal** [comment]
@mikebonnell Hope you are doing good. Did you get a chance to look at this?

**Comment by mikebonnell** [comment]
I haven't yet, but it is on our roadmap to take a look soon.

**Comment by jladieu** [comment]
@ayjindal I started working on this and and used the credentials you provided offline, however I was unable to find the admin panel to try and set up a WebHook endpoint.  I've tried finding it on both the web cilent and the Mac client -- can you give more specifics on how to get to this?  Thanks!

**Comment by ayjindal** [comment]
@jladieu Thanks for your time spent on this. :) 
Although I had setup a webhook already and mentioned its endpoint in the mail, I missed mentioning how to get around creating a webhook yourself. Sorry for that. You can reach the admin panel by clicking your avatar on the top right of the web/mac client (screenshot below) -> `Domain admin panel`. You can then follow [this doc](https://flockapi.atlassian.net/wiki/display/FlockAPI/Incoming+Webhook+-+UI+Configuration) to proceed further in creating an incoming webhook. Please let me know if you need anything else.

screen shot 2016-03-16 at 8 48 21 pm

**Comment by jladieu** [comment]
Thanks @ayjindal I'll give this a shot!

**Comment by jladieu** [comment]
Thanks @ayjindal - your directions worked like a charm.  I am getting this prepped and tested on an internal working branch but I am hoping to ship this today or tomorrow.  Will let you know here once this is wrapped up or if I bump into any other gotchas.

**Comment by jladieu** [comment]
@ayjindal This is shipped! I am closing this PR out in favor of the commit I prepped on our internal working branch.  Please take a look there for the final changeset: https://github.com/crashlytics/crashlytics-services/commit/32071586c62323c3787a5a1aac85cb9fec4bc711

Thanks so much for your help adding this awesome integration to Crashlytics!

**Comment by ayjindal** [comment]
@jladieu This is great news. Thank you very much.

**Comment by sktguha** [comment]
awesome @jladieu  (y)

**Pull request closed without merging**
