### PR TITLE
Added Github Enterprise Feature

### PR DESCRIPTION
**Pull request by patel-niket**
- This is based on OctoKit 4.0
- It has minor changes on function call to support github enterprise API. 
For Example, https://github.company.com/

### CODE REVIEW

**Comment by mikebonnell** [comment]
Thanks for this PR, can you also include a link to your Twitter account and a headshot to use for the credit of this?

**Comment by patel-niket** [comment]
Here you go, 
@patelniket
yafb3nex

**Comment by jladieu** [comment]
@patel-niket - I'd like to get started on integrating this, but we don't have a Github enterprise account to test this on, is it possible you could provide us the info for a test account that we could use for roundtrip verification?  Please email support@fabric.io with the details.

cc @mikebonnell

**Comment by patel-niket** [comment]
@jladieu @mikebonnell 

I've send the email invitation on support@fabric.io with Github Enterprise Account details and access to test org & repos. Please let me know if you need more information or access. Please feel free to create your own repo for testing.

**Comment by mikebonnell** [comment]
Perfect, thanks @patel-niket. Just got them!

**Comment by patelniket** [comment]
Hi, can someone please help remove me from this email chain and update the
email address? I think by mistake this email to sent to my GitHub user
email from @patelniket instead of the email of @patel-niket. Can someone
please help update it? This is spam for my inbox.

Thank you,
Niket Patel.
On Thu, Oct 15, 2015 at 15:22 mikebonnell <notifications@github.com> wrote:

> Perfect, thanks @patel-niket <https://github.com/patel-niket>. Just got
> them!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crashlytics/crashlytics-services/pull/101#issuecomment-148496199>
> .
>
-- 
Thank you,
Niket Patel

**Comment by mikebonnell** [comment]
Should be all set now Niket.

**Comment by patelniket** [comment]
Thank you!
On Thu, Oct 15, 2015 at 15:34 mikebonnell <notifications@github.com> wrote:

> Should be all set now Niket.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crashlytics/crashlytics-services/pull/101#issuecomment-148498716>
> .
>
-- 
Thank you,
Niket Patel

**Comment by jladieu** [comment]
@patelniket - just an FYI, I'm getting started on working on this and aiming to get it integrated in the next few days.  I'll keep you posted!

**Comment by jladieu** [comment]
Closing this PR out.  Further work on this is going to on our internal working branch https://github.com/crashlytics/crashlytics-services/pull/102, watch that PR for updates!

**Comment by patelniket** [comment]
Hi, I am still getting these spam emails, please refer to my older email
from the low quoted, you need to send email to GitHub user handle:
@patel-niket and not to @patelniket.

Thank you,
Niket.



"Hi, can someone please help remove me from this email chain and update the
email address? I think by mistake this email is sent to my GitHub user
email from @patelniket instead of the email of @patel-niket. Can someone
please help update it? This is spam for my inbox.

Thank you,
Niket Patel."

On Mon, Oct 19, 2015 at 09:50 Josh Ladieu <notifications@github.com> wrote:

> Closing this PR out. Further work on this is going to on our internal
> working branch #102
> <https://github.com/crashlytics/crashlytics-services/pull/102>, watch
> that PR for updates!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crashlytics/crashlytics-services/pull/101#issuecomment-149218807>
> .
>
-- 
Thank you,
Niket Patel

**Comment by jladieu** [comment]
Niket, sorry for the continued notifications.  Autocorrect keeps grabbing the wrong handle!  I will aim not to at-mention you again.

**Comment by jladieu** [comment]
@patel-niket - please follow https://github.com/crashlytics/crashlytics-services/issues/103 for progress on this.  Rather than implement Github Enterprise support as a new service hook, we will improve our existing Github integration to accept a domain override for our Github Enterprise customers.  Thank you so much for your help in raising our awareness of this feature.

**Comment by patelniket** [comment]
Hi Josh,

@patelniket here. Still I am getting these emails.
On Mon, Oct 19, 2015 at 12:55 Josh Ladieu <notifications@github.com> wrote:

> @patel-niket <https://github.com/patel-niket> - please follow #103
> <https://github.com/crashlytics/crashlytics-services/issues/103> for
> progress on this. Rather than implement Github Enterprise support as a new
> service hook, we will improve our existing Github integration to accept a
> domain override for our Github Enterprise customers. Thank you so much for
> your help in raising our awareness of this feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crashlytics/crashlytics-services/pull/101#issuecomment-149279265>
> .
>
-- 
Thank you,
Niket Patel

**Pull request closed without merging**
